on:
  pull_request:
    branches:
      - "*"

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "BUILD"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy fase 1
        run: echo "DEPLOY start"
      - name: desploy fase 2
        run: echo "DEPLOY end"

