on:
  push:
    branches:
      - "*"

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "BUILD"
